# Generated by Django 5.0.1 on 2024-02-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_user', models.CharField(max_length=200)),
                ('submitted_user', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='data submitted')),
                ('content', models.TextField()),
            ],
        ),
    ]
