# Generated by Django 5.0.1 on 2024-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data submitted'),
        ),
    ]
