# Generated by Django 5.0.1 on 2024-03-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_talk_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talk',
        ),
    ]
